# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    filter_sets:
        squared_thumbnail_small:
            quality: 50
            filters:
                relative_resize:
                    heighten: 96
                    allow_upscale: true
        squared_thumbnail_medium:
            quality: 50
            filters:
                relative_resize:
                    heighten: 300
                    allow_upscale: true
        big:
            quality: 70
            filters:
                relative_resize:
                    heighten: 500
                    allow_upscale: true
    loaders:
        flysystem_loader:
            flysystem:
                filesystem_service: oneup_flysystem.uploads_filesystem_filesystem
    data_loader: flysystem_loader
#    resolvers:
#        flysystem_resolver:
#            flysystem:
#                filesystem_service: oneup_flysystem.uploads_filesystem_filesystem
#                cache_prefix: media/cache
#                root_url: public/uploads
#    cache: flysystem_resolver