# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        uploads_adapter:
            local:
                directory: '%kernel.project_dir%/uploads'
    filesystems:
        uploads_filesystem:
            adapter: uploads_adapter
#            alias: League\Flysystem\Filesystem
